// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: spot_service.proto

package sport_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SportInstrumentService_ViewMarkets_FullMethodName = "/sport.SportInstrumentService/ViewMarkets"
)

// SportInstrumentServiceClient is the client API for SportInstrumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SportInstrumentServiceClient interface {
	ViewMarkets(ctx context.Context, in *ViewMarketsRequest, opts ...grpc.CallOption) (*ViewMarketsResponse, error)
}

type sportInstrumentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSportInstrumentServiceClient(cc grpc.ClientConnInterface) SportInstrumentServiceClient {
	return &sportInstrumentServiceClient{cc}
}

func (c *sportInstrumentServiceClient) ViewMarkets(ctx context.Context, in *ViewMarketsRequest, opts ...grpc.CallOption) (*ViewMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewMarketsResponse)
	err := c.cc.Invoke(ctx, SportInstrumentService_ViewMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SportInstrumentServiceServer is the server API for SportInstrumentService service.
// All implementations must embed UnimplementedSportInstrumentServiceServer
// for forward compatibility.
type SportInstrumentServiceServer interface {
	ViewMarkets(context.Context, *ViewMarketsRequest) (*ViewMarketsResponse, error)
	mustEmbedUnimplementedSportInstrumentServiceServer()
}

// UnimplementedSportInstrumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSportInstrumentServiceServer struct{}

func (UnimplementedSportInstrumentServiceServer) ViewMarkets(context.Context, *ViewMarketsRequest) (*ViewMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewMarkets not implemented")
}
func (UnimplementedSportInstrumentServiceServer) mustEmbedUnimplementedSportInstrumentServiceServer() {
}
func (UnimplementedSportInstrumentServiceServer) testEmbeddedByValue() {}

// UnsafeSportInstrumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SportInstrumentServiceServer will
// result in compilation errors.
type UnsafeSportInstrumentServiceServer interface {
	mustEmbedUnimplementedSportInstrumentServiceServer()
}

func RegisterSportInstrumentServiceServer(s grpc.ServiceRegistrar, srv SportInstrumentServiceServer) {
	// If the following call panics, it indicates UnimplementedSportInstrumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SportInstrumentService_ServiceDesc, srv)
}

func _SportInstrumentService_ViewMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportInstrumentServiceServer).ViewMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SportInstrumentService_ViewMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportInstrumentServiceServer).ViewMarkets(ctx, req.(*ViewMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SportInstrumentService_ServiceDesc is the grpc.ServiceDesc for SportInstrumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SportInstrumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sport.SportInstrumentService",
	HandlerType: (*SportInstrumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewMarkets",
			Handler:    _SportInstrumentService_ViewMarkets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spot_service.proto",
}
