// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: spot_service.proto

package sport_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     []string               `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_service_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMarketsRequest) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_service_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_spot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_spot_service_proto_rawDescGZIP(), []int{2}
}

func (x *Market) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Market) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Market) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_spot_service_proto protoreflect.FileDescriptor

const file_spot_service_proto_rawDesc = "" +
	"\n" +
	"\x12spot_service.proto\x12\x05sport\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\x12ViewMarketsRequest\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\tR\tuserRoles\">\n" +
	"\x13ViewMarketsResponse\x12'\n" +
	"\amarkets\x18\x01 \x03(\v2\r.sport.MarketR\amarkets\"\x81\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12>\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_at2^\n" +
	"\x16SportInstrumentService\x12D\n" +
	"\vViewMarkets\x12\x19.sport.ViewMarketsRequest\x1a\x1a.sport.ViewMarketsResponseB'Z%proto/pb/sportservicepb;sport_serviceb\x06proto3"

var (
	file_spot_service_proto_rawDescOnce sync.Once
	file_spot_service_proto_rawDescData []byte
)

func file_spot_service_proto_rawDescGZIP() []byte {
	file_spot_service_proto_rawDescOnce.Do(func() {
		file_spot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_service_proto_rawDesc), len(file_spot_service_proto_rawDesc)))
	})
	return file_spot_service_proto_rawDescData
}

var file_spot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_service_proto_goTypes = []any{
	(*ViewMarketsRequest)(nil),    // 0: sport.ViewMarketsRequest
	(*ViewMarketsResponse)(nil),   // 1: sport.ViewMarketsResponse
	(*Market)(nil),                // 2: sport.Market
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_spot_service_proto_depIdxs = []int32{
	2, // 0: sport.ViewMarketsResponse.markets:type_name -> sport.Market
	3, // 1: sport.Market.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 2: sport.SportInstrumentService.ViewMarkets:input_type -> sport.ViewMarketsRequest
	1, // 3: sport.SportInstrumentService.ViewMarkets:output_type -> sport.ViewMarketsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spot_service_proto_init() }
func file_spot_service_proto_init() {
	if File_spot_service_proto != nil {
		return
	}
	file_spot_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_service_proto_rawDesc), len(file_spot_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_service_proto_goTypes,
		DependencyIndexes: file_spot_service_proto_depIdxs,
		MessageInfos:      file_spot_service_proto_msgTypes,
	}.Build()
	File_spot_service_proto = out.File
	file_spot_service_proto_goTypes = nil
	file_spot_service_proto_depIdxs = nil
}
